<?php
namespace App\Controller;
 
use App\Controller\AppController;
use Cake\Event\EventInterface;
use App\Form\ContactForm;

/**
 * Contact Controller
 *
 */
class ContactController extends AppController
{
	public function beforeFilter(EventInterface $event)
    {
        $this->Auth->allow();
        parent::beforeFilter($event); // TODO: Change the autogenerated stub
    }

    public function index()
    {
        /*$contact = new ContactForm();
        if ($this->request->is('post')) {
            if ($contact->execute($this->request->getData())) {
                $this->Flash->success('Mensaje enviado. ¿Desea enviar otro menasje?');
                return $this->redirect(['controller' => 'Contact', 'action' => 'Index']);
            } else {
                $this->Flash->error('Hubo un problema enviando el fromulario. Por favor intente de nuevo.');
            }
        }
        $this->set('contact', $contact);*/
    }

    //$errors = $form->errors();
	/* $errors contains
	[
	    'email' => ['A valid email address is required']
	]
	*/
}